// Code generated by protoc-gen-go. DO NOT EDIT.
// source: organization.proto

package scytale_service_organization

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateOrganizationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrganizationRequest) Reset()         { *m = CreateOrganizationRequest{} }
func (m *CreateOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrganizationRequest) ProtoMessage()    {}
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{1}
}

func (m *CreateOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrganizationRequest.Unmarshal(m, b)
}
func (m *CreateOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrganizationRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrganizationRequest.Merge(m, src)
}
func (m *CreateOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrganizationRequest.Size(m)
}
func (m *CreateOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrganizationRequest proto.InternalMessageInfo

func (m *CreateOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrganizationRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OrganizationResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrganizationResponse) Reset()         { *m = OrganizationResponse{} }
func (m *OrganizationResponse) String() string { return proto.CompactTextString(m) }
func (*OrganizationResponse) ProtoMessage()    {}
func (*OrganizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{2}
}

func (m *OrganizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationResponse.Unmarshal(m, b)
}
func (m *OrganizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationResponse.Marshal(b, m, deterministic)
}
func (m *OrganizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationResponse.Merge(m, src)
}
func (m *OrganizationResponse) XXX_Size() int {
	return xxx_messageInfo_OrganizationResponse.Size(m)
}
func (m *OrganizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationResponse proto.InternalMessageInfo

func (m *OrganizationResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrganizationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrganizationResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OrganizationListResponse struct {
	Organizations        []*OrganizationResponse `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *OrganizationListResponse) Reset()         { *m = OrganizationListResponse{} }
func (m *OrganizationListResponse) String() string { return proto.CompactTextString(m) }
func (*OrganizationListResponse) ProtoMessage()    {}
func (*OrganizationListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{3}
}

func (m *OrganizationListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationListResponse.Unmarshal(m, b)
}
func (m *OrganizationListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationListResponse.Marshal(b, m, deterministic)
}
func (m *OrganizationListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationListResponse.Merge(m, src)
}
func (m *OrganizationListResponse) XXX_Size() int {
	return xxx_messageInfo_OrganizationListResponse.Size(m)
}
func (m *OrganizationListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationListResponse proto.InternalMessageInfo

func (m *OrganizationListResponse) GetOrganizations() []*OrganizationResponse {
	if m != nil {
		return m.Organizations
	}
	return nil
}

type CreateUserRequest struct {
	OrganizationId       string   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId       string   `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserListResponse struct {
	Users                []*UserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{6}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

type ByOrganizationRequest struct {
	OrganizationId       string   `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByOrganizationRequest) Reset()         { *m = ByOrganizationRequest{} }
func (m *ByOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*ByOrganizationRequest) ProtoMessage()    {}
func (*ByOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d10c68ef159b9ed, []int{7}
}

func (m *ByOrganizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByOrganizationRequest.Unmarshal(m, b)
}
func (m *ByOrganizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByOrganizationRequest.Marshal(b, m, deterministic)
}
func (m *ByOrganizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByOrganizationRequest.Merge(m, src)
}
func (m *ByOrganizationRequest) XXX_Size() int {
	return xxx_messageInfo_ByOrganizationRequest.Size(m)
}
func (m *ByOrganizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByOrganizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByOrganizationRequest proto.InternalMessageInfo

func (m *ByOrganizationRequest) GetOrganizationId() string {
	if m != nil {
		return m.OrganizationId
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "scytale.service.organization.Empty")
	proto.RegisterType((*CreateOrganizationRequest)(nil), "scytale.service.organization.CreateOrganizationRequest")
	proto.RegisterType((*OrganizationResponse)(nil), "scytale.service.organization.OrganizationResponse")
	proto.RegisterType((*OrganizationListResponse)(nil), "scytale.service.organization.OrganizationListResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "scytale.service.organization.CreateUserRequest")
	proto.RegisterType((*UserResponse)(nil), "scytale.service.organization.UserResponse")
	proto.RegisterType((*UserListResponse)(nil), "scytale.service.organization.UserListResponse")
	proto.RegisterType((*ByOrganizationRequest)(nil), "scytale.service.organization.ByOrganizationRequest")
}

func init() { proto.RegisterFile("organization.proto", fileDescriptor_8d10c68ef159b9ed) }

var fileDescriptor_8d10c68ef159b9ed = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xb4, 0x55, 0x9c, 0xda, 0xaa, 0xa3, 0x85, 0x58, 0x3d, 0x94, 0xf5, 0x60, 0xf1,
	0x10, 0xa1, 0x05, 0xbd, 0x16, 0x45, 0x41, 0x10, 0xd4, 0xa8, 0x20, 0x28, 0x48, 0x4c, 0x57, 0x5d,
	0xb4, 0x49, 0xdc, 0xdd, 0x16, 0xea, 0x55, 0xff, 0xaf, 0x7f, 0x41, 0x9a, 0xd8, 0xba, 0x69, 0x93,
	0x98, 0x7a, 0x0b, 0xbb, 0x93, 0x6f, 0xe6, 0xbd, 0x79, 0x09, 0xa0, 0xc7, 0x9f, 0x6c, 0x97, 0xbd,
	0xdb, 0x92, 0x79, 0xae, 0xe9, 0x73, 0x4f, 0x7a, 0xb8, 0x29, 0x9c, 0x81, 0xb4, 0x5f, 0xa9, 0x29,
	0x28, 0xef, 0x33, 0x87, 0x9a, 0x6a, 0x0d, 0x99, 0x87, 0xe2, 0x51, 0xd7, 0x97, 0x03, 0x72, 0x01,
	0xeb, 0x87, 0x9c, 0xda, 0x92, 0x9e, 0x29, 0xd7, 0x16, 0x7d, 0xeb, 0x51, 0x21, 0x11, 0xa1, 0xe0,
	0xda, 0x5d, 0x6a, 0x68, 0x75, 0xad, 0xb1, 0x60, 0x05, 0xcf, 0x58, 0x87, 0x52, 0x87, 0x0a, 0x87,
	0x33, 0x7f, 0x58, 0x69, 0xe8, 0xc1, 0x95, 0x7a, 0x44, 0xee, 0x60, 0x2d, 0x0a, 0x13, 0xbe, 0xe7,
	0x0a, 0x8a, 0x15, 0xd0, 0x59, 0xe7, 0x87, 0xa5, 0xb3, 0xce, 0x98, 0xae, 0x27, 0xd3, 0xf3, 0xd3,
	0x74, 0x09, 0x86, 0x4a, 0x3f, 0x65, 0x42, 0x8e, 0x3b, 0xdc, 0x40, 0x59, 0x55, 0x29, 0x0c, 0xad,
	0x9e, 0x6f, 0x94, 0x9a, 0x4d, 0x33, 0xcd, 0x0b, 0x33, 0x6e, 0x58, 0x2b, 0x0a, 0x22, 0xe7, 0xb0,
	0x12, 0xda, 0x74, 0x2d, 0x28, 0x1f, 0xd9, 0xb3, 0x0d, 0x4b, 0x6a, 0xd5, 0xfd, 0x58, 0x5d, 0x45,
	0x3d, 0x3e, 0x89, 0x55, 0x4a, 0x6e, 0x61, 0x31, 0x64, 0x25, 0xb8, 0x13, 0x03, 0xd7, 0x53, 0xe1,
	0x79, 0x05, 0x7e, 0x05, 0xcb, 0x43, 0x78, 0xc4, 0x9c, 0x36, 0x14, 0x7b, 0x82, 0xf2, 0x91, 0x29,
	0x3b, 0xe9, 0xa6, 0xa8, 0xb3, 0x59, 0xe1, 0x8b, 0xa4, 0x0d, 0xd5, 0x83, 0x41, 0x5c, 0x4e, 0xb2,
	0x1a, 0xd1, 0xfc, 0x2a, 0xc0, 0xaa, 0x0a, 0xb8, 0x0c, 0x5b, 0xe3, 0x87, 0x06, 0x38, 0x1d, 0x43,
	0xdc, 0x4f, 0x9f, 0x31, 0x31, 0xb8, 0xb5, 0x7f, 0x6c, 0x9c, 0xe4, 0xb0, 0x0f, 0xd5, 0x63, 0x2a,
	0x9d, 0xe7, 0xc9, 0x7c, 0xe1, 0x56, 0x3a, 0x2e, 0xf8, 0x92, 0x6a, 0x7b, 0xd9, 0x7b, 0xaa, 0x7b,
	0x21, 0x39, 0x7c, 0x01, 0xf8, 0x0d, 0x17, 0xee, 0x66, 0x11, 0xad, 0xc4, 0xb0, 0x36, 0xc3, 0x26,
	0x49, 0x0e, 0x1f, 0xa1, 0x1c, 0x88, 0x1c, 0xe5, 0x23, 0x9b, 0x38, 0xf3, 0xef, 0x1e, 0x13, 0xa2,
	0x3e, 0x35, 0xd8, 0x88, 0x34, 0x8a, 0x46, 0x07, 0x5b, 0xe9, 0xc4, 0xd8, 0xa0, 0xcd, 0x3e, 0xc6,
	0xc3, 0x5c, 0xf0, 0x37, 0x6c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x00, 0x63, 0xdd, 0x23,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrganizationServiceClient is the client API for OrganizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrganizationServiceClient interface {
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*OrganizationResponse, error)
	FetchOrganizationList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganizationListResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	FetchUserList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserListResponse, error)
	FetchUserListByOrganization(ctx context.Context, in *ByOrganizationRequest, opts ...grpc.CallOption) (*UserListResponse, error)
}

type organizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationServiceClient(cc *grpc.ClientConn) OrganizationServiceClient {
	return &organizationServiceClient{cc}
}

func (c *organizationServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*OrganizationResponse, error) {
	out := new(OrganizationResponse)
	err := c.cc.Invoke(ctx, "/scytale.service.organization.OrganizationService/CreateOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) FetchOrganizationList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OrganizationListResponse, error) {
	out := new(OrganizationListResponse)
	err := c.cc.Invoke(ctx, "/scytale.service.organization.OrganizationService/FetchOrganizationList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/scytale.service.organization.OrganizationService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) FetchUserList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/scytale.service.organization.OrganizationService/FetchUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationServiceClient) FetchUserListByOrganization(ctx context.Context, in *ByOrganizationRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/scytale.service.organization.OrganizationService/FetchUserListByOrganization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationServiceServer is the server API for OrganizationService service.
type OrganizationServiceServer interface {
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*OrganizationResponse, error)
	FetchOrganizationList(context.Context, *Empty) (*OrganizationListResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
	FetchUserList(context.Context, *Empty) (*UserListResponse, error)
	FetchUserListByOrganization(context.Context, *ByOrganizationRequest) (*UserListResponse, error)
}

func RegisterOrganizationServiceServer(s *grpc.Server, srv OrganizationServiceServer) {
	s.RegisterService(&_OrganizationService_serviceDesc, srv)
}

func _OrganizationService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scytale.service.organization.OrganizationService/CreateOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_FetchOrganizationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).FetchOrganizationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scytale.service.organization.OrganizationService/FetchOrganizationList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).FetchOrganizationList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scytale.service.organization.OrganizationService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_FetchUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).FetchUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scytale.service.organization.OrganizationService/FetchUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).FetchUserList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrganizationService_FetchUserListByOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationServiceServer).FetchUserListByOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scytale.service.organization.OrganizationService/FetchUserListByOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationServiceServer).FetchUserListByOrganization(ctx, req.(*ByOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrganizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scytale.service.organization.OrganizationService",
	HandlerType: (*OrganizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrganization",
			Handler:    _OrganizationService_CreateOrganization_Handler,
		},
		{
			MethodName: "FetchOrganizationList",
			Handler:    _OrganizationService_FetchOrganizationList_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _OrganizationService_CreateUser_Handler,
		},
		{
			MethodName: "FetchUserList",
			Handler:    _OrganizationService_FetchUserList_Handler,
		},
		{
			MethodName: "FetchUserListByOrganization",
			Handler:    _OrganizationService_FetchUserListByOrganization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organization.proto",
}
